services:
  - type: web
    name: yt-downloader
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3-pip ffmpeg
      pip3 install yt-dlp
      npm install
    startCommand: node server.js
